version: "3.4"

services:
  whisper-asr-webservice:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASR_MODEL=base
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app/app
      - cache-whisper:/root/.cache

volumes:
  cache-whisper: